version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    hostname: mediawala
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 16881:6881
      - 16881:6881/udp
      - 18085:18085 # qbittorrent
      - 18989:8989 #sonarr
      - 17878:7878 #raddar
      - 19696:9696 #prowlarr
      - 15055:5055 # jellyseer
    volumes:
      - /home/ubuntu/docker/arr-stack:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard
      # OpenVPN:
      # - OPENVPN_USER=
      # - OPENVPN_PASSWORD=
      # Wireguard:
      - WIREGUARD_PRIVATE_KEY=${vpn_key} # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/nordvpn.md#obtain-your-wireguard-private-key
      - WIREGUARD_ADDRESSES=10.5.0.2/32
      # Timezone for accurate log times
      - TZ=Asia/Kolkata
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=24h
    restart: always

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=Asia/Kolkata
      - WEBUI_PORT=18085
    volumes:
      - /home/harshit/docker/configs/qbit:/config
      - /mnt/nfs/Streaming/downloads/torrent:/data/torrents
      - /mnt/nfs/Streaming:/data/media
    depends_on:
      - gluetun
    restart: always

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=Etc/UTC
    volumes:
      - /home/harshit/docker/configs/sonarr:/config
      - /mnt/nfs/Streaming:/media #optional
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: "service:gluetun"
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=Etc/UTC
    volumes:
      - /home/harshit/docker/configs/radarr:/config
      - /mnt/nfs/Streaming:/media #optional
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=Etc/UTC
    volumes:
      - /home/harshit/docker/configs/prowlarr:/config
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    network_mode: "service:gluetun"
    environment:
        - LOG_LEVEL=debug
        - TZ=Asia/Tashkent
    volumes:
        - /home/harshit/docker/configs/jellyseerr:/config
    restart: unless-stopped  